<?php

namespace App\Services;

use DOMDocument;
use DOMElement;
use ZipArchive;

class DocxAutoFixService
{
    /**
     * Process an exported or uploaded DOCX file, removing layout table borders,
     * reformatting margins, page size (A4), fixing XML ampersands, forcing standard 
     * Print Layout view (page mode), and automatically splitting and styling 
     * Gujarati and English text runs.
     *
     * @param string $filePath Absolute path to the .docx file
     * @param string $gujaratiFont Font family name for Gujarati text
     * @param string $englishFont Font family name for English text
     * @return bool Success status
     */
    public static function autoFixDocx(string $filePath, string $gujaratiFont = 'Noto Sans Gujarati', string $englishFont = 'Times New Roman'): bool
    {
        if (!file_exists($filePath)) {
            return false;
        }

        $zip = new ZipArchive();
        if ($zip->open($filePath) !== true) {
            return false;
        }

        // 1. Read and fix XML ampersands in document.xml
        $xmlContent = $zip->getFromName('word/document.xml');
        if (!$xmlContent) {
            $zip->close();
            return false;
        }

        // Sanitize unescaped ampersands in raw XML generated by PHPWord
        $xmlContent = preg_replace('/&(?!(amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/u', '&amp;', $xmlContent);

        $dom = new DOMDocument();
        libxml_use_internal_errors(true);
        if (!$dom->loadXML($xmlContent)) {
            libxml_clear_errors();
            $zip->close();
            return false;
        }
        libxml_clear_errors();

        // 2. Remove visible borders on layout tables and their cells
        $tables = $dom->getElementsByTagName('tbl');
        foreach ($tables as $tbl) {
            $tblPr = $tbl->getElementsByTagName('tblPr')->item(0);
            if (!$tblPr) {
                $tblPr = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:tblPr');
                $tbl->insertBefore($tblPr, $tbl->firstChild);
            }

            // Remove existing tblBorders and apply clean none borders
            $oldBorders = $tblPr->getElementsByTagName('tblBorders')->item(0);
            if ($oldBorders) {
                $tblPr->removeChild($oldBorders);
            }
            
            $tblBorders = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:tblBorders');
            foreach (['top', 'left', 'bottom', 'right', 'insideH', 'insideV'] as $side) {
                $b = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:' . $side);
                $b->setAttribute('w:val', 'none');
                $b->setAttribute('w:sz', '0');
                $b->setAttribute('w:space', '0');
                $b->setAttribute('w:color', 'auto');
                $tblBorders->appendChild($b);
            }
            $tblPr->appendChild($tblBorders);

            // Also remove borders on every cell <w:tcPr>
            $tcs = $tbl->getElementsByTagName('tc');
            foreach ($tcs as $tc) {
                $tcPr = $tc->getElementsByTagName('tcPr')->item(0);
                if (!$tcPr) {
                    $tcPr = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:tcPr');
                    $tc->insertBefore($tcPr, $tc->firstChild);
                }
                $oldTcBorders = $tcPr->getElementsByTagName('tcBorders')->item(0);
                if ($oldTcBorders) {
                    $tcPr->removeChild($oldTcBorders);
                }
                $tcBorders = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:tcBorders');
                foreach (['top', 'left', 'bottom', 'right'] as $side) {
                    $b = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:' . $side);
                    $b->setAttribute('w:val', 'none');
                    $b->setAttribute('w:sz', '0');
                    $b->setAttribute('w:space', '0');
                    $b->setAttribute('w:color', 'auto');
                    $tcBorders->appendChild($b);
                }
                $tcPr->appendChild($tcBorders);
            }
        }

        // 3. Enforce Page Size (A4: 21cm x 29.7cm) and Margins (4cm Left/Right, 2cm Top/Bottom)
        // Margins in dxa: 2cm = 1134 dxa, 4cm = 2268 dxa
        // Page Size in dxa: A4 is 210mm x 297mm -> 11906 x 16838 dxa
        $sectPrs = $dom->getElementsByTagName('sectPr');
        
        if ($sectPrs->length === 0) {
            $body = $dom->getElementsByTagName('body')->item(0);
            if ($body) {
                $newSect = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:sectPr');
                $body->appendChild($newSect);
                $sectPrs = $dom->getElementsByTagName('sectPr');
            }
        }

        foreach ($sectPrs as $sectPr) {
            // Find or create pgSz (A4 Portrait)
            $pgSz = $sectPr->getElementsByTagName('pgSz')->item(0);
            if (!$pgSz) {
                $pgSz = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:pgSz');
                $sectPr->appendChild($pgSz);
            }
            $pgSz->setAttribute('w:w', '11906');
            $pgSz->setAttribute('w:h', '16838');
            $pgSz->setAttribute('w:code', '9');
            $pgSz->removeAttribute('w:orient'); // Portrait

            // Find or create pgMar
            $pgMar = $sectPr->getElementsByTagName('pgMar')->item(0);
            if (!$pgMar) {
                $pgMar = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:pgMar');
                $sectPr->appendChild($pgMar);
            }
            $pgMar->setAttribute('w:top', '1134');
            $pgMar->setAttribute('w:bottom', '1134');
            $pgMar->setAttribute('w:left', '2268');
            $pgMar->setAttribute('w:right', '2268');
            $pgMar->setAttribute('w:header', '720');
            $pgMar->setAttribute('w:footer', '720');
            $pgMar->setAttribute('w:gutter', '0');
        }

        // 3.5. Convert Legacy Gujarati Fonts (TitleLightTwo, TitleLight, TitleTwo, AbhayTwo) to Unicode Gujarati
        $runs = $dom->getElementsByTagName('r');
        $legacyFonts = ['titlelighttwo', 'titlelight', 'titletwo', 'abhaytwo'];
        
        foreach ($runs as $run) {
            if (!$run instanceof DOMElement) continue;

            $rPr = $run->getElementsByTagName('rPr')->item(0);
            if (!$rPr) continue;

            $rFonts = $rPr->getElementsByTagName('rFonts')->item(0);
            if (!$rFonts) continue;

            $isLegacyFont = false;
            foreach (['ascii', 'hAnsi', 'eastAsia', 'cs'] as $attr) {
                $fontAttr = $rFonts->getAttribute('w:' . $attr);
                if ($fontAttr && in_array(strtolower(trim($fontAttr)), $legacyFonts)) {
                    $isLegacyFont = true;
                    break;
                }
            }

            if ($isLegacyFont) {
                $tElements = $run->getElementsByTagName('t');
                if ($tElements->length > 0) {
                    $tNodes = [];
                    foreach ($tElements as $tEl) {
                        $tNodes[] = $tEl;
                    }
                    
                    $originalText = '';
                    foreach ($tNodes as $tEl) {
                        $originalText .= $tEl->textContent;
                    }

                    // Convert legacy Gujarati to Unicode
                    $unicodeText = LegacyGujaratiConverterService::convertLMG($originalText);

                    // Update the first t element and remove others
                    $firstT = $tNodes[0];
                    while ($firstT->hasChildNodes()) {
                        $firstT->removeChild($firstT->firstChild);
                    }
                    $firstT->appendChild($dom->createTextNode($unicodeText));
                    $firstT->setAttribute('xml:space', 'preserve');

                    for ($i = 1; $i < count($tNodes); $i++) {
                        $parentOfT = $tNodes[$i]->parentNode;
                        if ($parentOfT) {
                            $parentOfT->removeChild($tNodes[$i]);
                        }
                    }
                }

                // Update fonts to the selected Gujarati font
                $rFonts->setAttribute('w:ascii', $gujaratiFont);
                $rFonts->setAttribute('w:hAnsi', $gujaratiFont);
                $rFonts->setAttribute('w:eastAsia', $gujaratiFont);
                $rFonts->setAttribute('w:cs', $gujaratiFont);

                // Set font size to 13pt (26 half-points)
                $sz = $rPr->getElementsByTagName('sz')->item(0);
                if (!$sz) {
                    $sz = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:sz');
                    $rPr->appendChild($sz);
                }
                $sz->setAttribute('w:val', '26');

                $szCs = $rPr->getElementsByTagName('szCs')->item(0);
                if (!$szCs) {
                    $szCs = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:szCs');
                    $rPr->appendChild($szCs);
                }
                $szCs->setAttribute('w:val', '26');
            }
        }

        // 4. Process runs to split Gujarati and English scripts
        $runs = $dom->getElementsByTagName('r');
        $runsToReplace = [];

        foreach ($runs as $run) {
            if (!$run instanceof DOMElement) continue;

            $t = $run->getElementsByTagName('t')->item(0);
            if (!$t) continue;

            $text = $t->textContent;
            if ($text === '') continue;

            $hasGujarati = preg_match('/[\x{0A80}-\x{0AFF}]/u', $text);
            $hasEnglish = preg_match('/[a-zA-Z]/u', $text);

            if ($hasGujarati || $hasEnglish) {
                $runsToReplace[] = [
                    'element' => $run,
                    'text' => $text,
                ];
            }
        }

        foreach ($runsToReplace as $item) {
            $runEl = $item['element'];
            $text = $item['text'];
            $parent = $runEl->parentNode;
            if (!$parent) continue;

            $parts = preg_split('/([\x{0A80}-\x{0AFF}]+)/u', $text, -1, PREG_SPLIT_DELIM_CAPTURE);

            foreach ($parts as $part) {
                if ($part === '') continue;

                $isGuj = preg_match('/[\x{0A80}-\x{0AFF}]/u', $part);
                $fontName = $isGuj ? $gujaratiFont : $englishFont;

                // Clone run to preserve all attributes and layout properties safely
                $newRun = $runEl->cloneNode(true);

                $rPr = $newRun->getElementsByTagName('rPr')->item(0);
                if (!$rPr) {
                    $rPr = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:rPr');
                    $newRun->insertBefore($rPr, $newRun->firstChild);
                }

                $rFonts = $rPr->getElementsByTagName('rFonts')->item(0);
                if (!$rFonts) {
                    $rFonts = $dom->createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main', 'w:rFonts');
                    $rPr->appendChild($rFonts);
                }
                $rFonts->setAttribute('w:ascii', $fontName);
                $rFonts->setAttribute('w:hAnsi', $fontName);
                $rFonts->setAttribute('w:eastAsia', $fontName);
                $rFonts->setAttribute('w:cs', $fontName);

                $t = $newRun->getElementsByTagName('t')->item(0);
                if ($t) {
                    while ($t->hasChildNodes()) {
                        $t->removeChild($t->firstChild);
                    }
                    $t->setAttribute('xml:space', 'preserve');
                    $t->appendChild($dom->createTextNode($part));
                }

                $parent->insertBefore($newRun, $runEl);
            }

            $parent->removeChild($runEl);
        }

        // 5. Save document.xml back to zip
        $zip->addFromString('word/document.xml', $dom->saveXML());

        // 6. Force standard "Print Layout" View (A4 Page Sheet view) in word/settings.xml
        $cleanSettings = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
    <w:view w:val="print"/>
    <w:zoom w:percent="100"/>
    <w:defaultTabStop w:val="720"/>
    <w:compat>
        <w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/>
    </w:compat>
</w:settings>';
        $zip->addFromString('word/settings.xml', $cleanSettings);

        $zip->close();
        return true;
    }
}
